### ISSUE TITLE
Probleme bei Installation am Synology NAS

### ISSUE THREAD

**Issue by fabianekc** [soudis/datencockpit-docker#1]
Ich habe mit der Anleitung erfolgreich das Datencockpit auf meinem MacBook installieren können. Bei gleichem Dockerfile und docker-compose.yml tritt allerdings ein Fehler auf meinem Synology NAS auf:
![datencockpit](https://user-images.githubusercontent.com/2848088/40332457-772c3fea-5d54-11e8-85d4-102c6bbf4b79.png)

MacBook: Docker version 18.03.1-ce, build 9ee9f40
Synology DS1517+: Docker version 17.05.0-ce, build 9f07f0e-synology

Scheinbar kann sich auf dem NAS der datencockpit-Container nicht mit dem db-Container verbinden. Gibt es eine Anleitung, wie man die Konfiguration zur Verbindung prüfen und nachträglich setzen kann?

Danke im voraus für jegliche Hinweise!

**Comment by soudis** [comment]
man kann mit 

`docker-compose logs datencockpit`

die Logfiles nachschauen oder mit

`docker-compose exec datencockpit bash `

in den Container einsteigen. Vielleicht lässt sich so was rausfinden. Ansonsten hab ich keine Idee was da schieflaufen könnte

**Comment by fabianekc** [comment]
Habe auch gerade Bernhard geschrieben und er hat mir den Tipp gegeben, in LocalSettings.php nachzusehen. Interessanterweise waren dort die Verbindungsdaten nicht angegeben:
$wgDBserver, ...
Nachdem ich die Credentials eingegeben habe, startet die Seite.

Danke jedenfalls für die Antwort! Ticket kann gerne geschlossen werden.
