### ISSUE TITLE
Update für Version 1.0

### ISSUE THREAD

**Issue by krabina** [soudis/datencockpit-docker#2]
Hi,
wäre super, wenn der Docker-Containter die aktuellste Version beinhalten würde.

Bitte übrigens um Kontaktaufnahme an krabina[at]kdz.or.at - habe eine Frage.
lg, Bernhard

**Comment by ovizii** [comment]
Fänd ich auch toll ;-)

**Comment by ovizii** [comment]
gerade nachgeschaut und in dem Dockerfile steht:

`RUN wget https://github.com/krabina/Datencockpit/archive/1.0.tar.gz && tar -xzvf 1.0.tar.gz --strip-components=1`

d.h. das müßte doch schon die aktuelle Datencockpit Version sein, oder?

**Comment by krabina** [comment]
ja, @soudis hat mir bestätigt, dass er es aktualisiert hat. Danke dafür!
