### ISSUE TITLE
getting error 403 when accessing my container

### ISSUE THREAD

**Issue by ovizii** [soudis/datencockpit-docker#5]
I know I had tried to heavily modify your docker-compose file so to see if my mods created this issue I went back and left your settings more or less unmodified. 
Here is my current docker-compose.yml: https://pastebin.com/M6eEz0iv basically all I did was change the public port. 

it builds successfully then I start the containers and get: error 403 when trying to access it via apps.mydomain.tld:8888

`datencockpit_1  | [Tue Jul 17 08:27:59.983144 2018] [autoindex:error] [pid 16] [client 51.254.xxx.xxx:63892] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive`

Any ideas?

**Comment by soudis** [comment]
Sorry, there was an error in the URL of the datencockpit package after the update to 1.0. Please try again, I changed the Dockerfile accordingly, I tried with you compose file and it worked.

Sorry, if you wasted a lot of time cause of this...

**Comment by ovizii** [comment]
Thanks, it works now.
